
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/cespare/xxhash"
  version = "1.0.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "~3.2.9"

[[constraint]]
  name = "github.com/coreos/pkg"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/gorilla/handlers"

[[constraint]]
  name = "github.com/gorilla/mux"

[[constraint]]
  name = "github.com/justinas/alice"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/pborman/uuid"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/rasky/go-xdr"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/soheilhy/cmux"
  version = "0.1.3"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/thejerf/suture"
  version = "2.0.0"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/sys"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.0.4"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "0.5.2"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
